require("fs")
    .readFileSync(process.argv[2], { encoding: "utf-8" })
    .replace(/\r\n/g, "\n")
    .split("\n\n")
    .map(s => new Set(s.replace(/[^a-z]/g, "")).size)
    .reduce((a, b) => a + b, 0)
    .toString()
    .split(" ")
    .forEach(s => console.log(s))
